api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
    eager_loading:
        enabled: true
#    collection:
#        pagination:
#            page_parameter_name: _page
#            pagination_client_item_per_page: true

    exception_to_status:
        App\Exception\EmptyBodyException: 400
        App\Exception\InvalidConfirmationTokenException: 404
