vich_uploader:
    db_driver: orm
    mappings:
        product_image:
            uri_prefix: /images
            upload_destination: '%kernel.project_dir%/public/images'
            #decide how uploaded files would be renamed
            namer: Vich\UploaderBundle\Naming\UniqidNamer

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
